// proto/agent_service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: agent_service.proto

package agentservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Message Definitions remain the same ---
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{0}
}

// ... (rest of the message definitions: PingRequest, FeatureExtractRequest, etc.)
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type FeatureExtractRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PageUrl          string                 `protobuf:"bytes,1,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	PageText         string                 `protobuf:"bytes,2,opt,name=page_text,json=pageText,proto3" json:"page_text,omitempty"`                         // Clean plain text content of the current page
	ExtractionFields []string               `protobuf:"bytes,3,rep,name=extraction_fields,json=extractionFields,proto3" json:"extraction_fields,omitempty"` // List of fields the user wants to extract
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeatureExtractRequest) Reset() {
	*x = FeatureExtractRequest{}
	mi := &file_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureExtractRequest) ProtoMessage() {}

func (x *FeatureExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureExtractRequest.ProtoReflect.Descriptor instead.
func (*FeatureExtractRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *FeatureExtractRequest) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

func (x *FeatureExtractRequest) GetPageText() string {
	if x != nil {
		return x.PageText
	}
	return ""
}

func (x *FeatureExtractRequest) GetExtractionFields() []string {
	if x != nil {
		return x.ExtractionFields
	}
	return nil
}

type FeatureExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtractedJson string                 `protobuf:"bytes,1,opt,name=extracted_json,json=extractedJson,proto3" json:"extracted_json,omitempty"` // AI's returned structured JSON string
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`    // Error message if extraction fails
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureExtractResponse) Reset() {
	*x = FeatureExtractResponse{}
	mi := &file_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureExtractResponse) ProtoMessage() {}

func (x *FeatureExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureExtractResponse.ProtoReflect.Descriptor instead.
func (*FeatureExtractResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *FeatureExtractResponse) GetExtractedJson() string {
	if x != nil {
		return x.ExtractedJson
	}
	return ""
}

func (x *FeatureExtractResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExtractedRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp         string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Url               string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	ExtractedDataJson string                 `protobuf:"bytes,4,opt,name=extracted_data_json,json=extractedDataJson,proto3" json:"extracted_data_json,omitempty"` // Stores the extracted JSON result
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExtractedRecord) Reset() {
	*x = ExtractedRecord{}
	mi := &file_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractedRecord) ProtoMessage() {}

func (x *ExtractedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractedRecord.ProtoReflect.Descriptor instead.
func (*ExtractedRecord) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *ExtractedRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtractedRecord) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ExtractedRecord) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExtractedRecord) GetExtractedDataJson() string {
	if x != nil {
		return x.ExtractedDataJson
	}
	return ""
}

type ExtractionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ExtractedRecord     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractionHistoryResponse) Reset() {
	*x = ExtractionHistoryResponse{}
	mi := &file_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractionHistoryResponse) ProtoMessage() {}

func (x *ExtractionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractionHistoryResponse.ProtoReflect.Descriptor instead.
func (*ExtractionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *ExtractionHistoryResponse) GetRecords() []*ExtractedRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_agent_service_proto protoreflect.FileDescriptor

const file_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x13agent_service.proto\x12\ragent_service\"\a\n" +
	"\x05Empty\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"|\n" +
	"\x15FeatureExtractRequest\x12\x19\n" +
	"\bpage_url\x18\x01 \x01(\tR\apageUrl\x12\x1b\n" +
	"\tpage_text\x18\x02 \x01(\tR\bpageText\x12+\n" +
	"\x11extraction_fields\x18\x03 \x03(\tR\x10extractionFields\"d\n" +
	"\x16FeatureExtractResponse\x12%\n" +
	"\x0eextracted_json\x18\x01 \x01(\tR\rextractedJson\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x81\x01\n" +
	"\x0fExtractedRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12.\n" +
	"\x13extracted_data_json\x18\x04 \x01(\tR\x11extractedDataJson\"U\n" +
	"\x19ExtractionHistoryResponse\x128\n" +
	"\arecords\x18\x01 \x03(\v2\x1e.agent_service.ExtractedRecordR\arecords2\xd1\x02\n" +
	"\tAIService\x12?\n" +
	"\x04Ping\x12\x1a.agent_service.PingRequest\x1a\x1b.agent_service.PingResponse\x12^\n" +
	"\x0fExtractFeatures\x12$.agent_service.FeatureExtractRequest\x1a%.agent_service.FeatureExtractResponse\x12K\n" +
	"\x13SaveExtractedRecord\x12\x1e.agent_service.ExtractedRecord\x1a\x14.agent_service.Empty\x12V\n" +
	"\x14GetExtractionHistory\x12\x14.agent_service.Empty\x1a(.agent_service.ExtractionHistoryResponseBAZ?github.com/kaili-yang/structView-agent/backend/pkg/agentserviceb\x06proto3"

var (
	file_agent_service_proto_rawDescOnce sync.Once
	file_agent_service_proto_rawDescData []byte
)

func file_agent_service_proto_rawDescGZIP() []byte {
	file_agent_service_proto_rawDescOnce.Do(func() {
		file_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)))
	})
	return file_agent_service_proto_rawDescData
}

var file_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_service_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: agent_service.Empty
	(*PingRequest)(nil),               // 1: agent_service.PingRequest
	(*PingResponse)(nil),              // 2: agent_service.PingResponse
	(*FeatureExtractRequest)(nil),     // 3: agent_service.FeatureExtractRequest
	(*FeatureExtractResponse)(nil),    // 4: agent_service.FeatureExtractResponse
	(*ExtractedRecord)(nil),           // 5: agent_service.ExtractedRecord
	(*ExtractionHistoryResponse)(nil), // 6: agent_service.ExtractionHistoryResponse
}
var file_agent_service_proto_depIdxs = []int32{
	5, // 0: agent_service.ExtractionHistoryResponse.records:type_name -> agent_service.ExtractedRecord
	1, // 1: agent_service.AIService.Ping:input_type -> agent_service.PingRequest
	3, // 2: agent_service.AIService.ExtractFeatures:input_type -> agent_service.FeatureExtractRequest
	5, // 3: agent_service.AIService.SaveExtractedRecord:input_type -> agent_service.ExtractedRecord
	0, // 4: agent_service.AIService.GetExtractionHistory:input_type -> agent_service.Empty
	2, // 5: agent_service.AIService.Ping:output_type -> agent_service.PingResponse
	4, // 6: agent_service.AIService.ExtractFeatures:output_type -> agent_service.FeatureExtractResponse
	0, // 7: agent_service.AIService.SaveExtractedRecord:output_type -> agent_service.Empty
	6, // 8: agent_service.AIService.GetExtractionHistory:output_type -> agent_service.ExtractionHistoryResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_service_proto_init() }
func file_agent_service_proto_init() {
	if File_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_service_proto_goTypes,
		DependencyIndexes: file_agent_service_proto_depIdxs,
		MessageInfos:      file_agent_service_proto_msgTypes,
	}.Build()
	File_agent_service_proto = out.File
	file_agent_service_proto_goTypes = nil
	file_agent_service_proto_depIdxs = nil
}
